// Generated by vite-plugin-mediapipe-assets.ts from the installed @mediapipe/hands package.
declare module 'virtual:mediapipe-hands-assets' {
  /** Byte size of each self-hosted MediaPipe Hands runtime file, keyed by file name. */
  export const MEDIAPIPE_FILE_SIZES: Readonly<Record<string, number>>;
}
